
SELECT YEAR(SALES_DATE) AS YEAR , MONTH(SALES_DATE) AS MONTH, GENDER , COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
INNER JOIN ONLINE_SALE O
ON I.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR,MONTH,GENDER
