SELECT  C.CAR_ID, C.CAR_TYPE , ROUND(DAILY_FEE * 30/100*(100-DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT iN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE END_DATE >'2022-11-00' AND START_DATE <'2022-12-00')
                      AND C.CAR_TYPE in ('세단', 'SUV')
            HAVING FEE >=500000 AND FEE<2000000
            ORDER BY FEE DESC, CAR_TYPE , CAR_ID DESC
            
                     