SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) AS PUCHASED_RATIO
FROM USER_INFO I INNER JOIN ONLINE_SALE O
ON I.USER_ID = O.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY MONTH
ORDER BY YEAR , MONTH


