WITH RECURSIVE TIME AS(
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR+1 FROM TIME WHERE HOUR<23)

SELECT HOUR , (0) AS COUNT FROM TIME WHERE HOUR NOT IN
(SELECT HOUR(DATETIME) AS HOUR FROM ANIMAL_OUTS GROUP BY HOUR
HAVING COUNT(*)>0)
UNION ALL
SELECT HOUR(DATETIME)AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR
ORDER BY HOUR