SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES 
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES 