
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
                               GROUP BY CATEGORY) S
                            ON   F.CATEGORY = S.CATEGORY AND F.PRICE = S.PRICE
WHERE F.CATEGORY REGEXP ('과자|국|김치|식용유')
ORDER BY F.PRICE DESC