
SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P 
INNER JOIN (SELECT MAX(PRICE)AS PRICE,  CATEGORY FROM FOOD_PRODUCT GROUP BY CATEGORY) C
ON P.CATEGORY = C.CATEGORY AND P.PRICE = C.PRICE
WHERE P.CATEGORY REGEXP "^(과자|국|김치|식용유)$"
ORDER BY MAX_PRICE DESC