
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F INNER JOIN (SELECT MAX(PRICE) AS PRICE, CATEGORY FROM FOOD_PRODUCT
                             GROUP BY CATEGORY) C
ON F.CATEGORY = C.CATEGORY AND F.PRICE = C.PRICE
WHERE F.CATEGORY REGEXP ('과자|국|김치|식용유')
ORDER BY MAX_PRICE DESC