SELECT MEMBER_NAME , REVIEW_TEXT , DATE_FORMAT(REVIEW_DATE ,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M , REST_REVIEW R
WHERE M.MEMBER_ID = R.MEMBER_ID
AND M.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(REVIEW_TEXT) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT