
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES FROM PRODUCT P
INNER JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY O.PRODUCT_ID 
ORDER BY SUM(PRICE * SALES_AMOUNT) DESC , PRODUCT_CODE