SELECT F.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT)TOTAL_SALES
FROM FOOD_PRODUCT F INNER JOIN FOOD_ORDER O 
ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) AND MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC , PRODUCT_ID