SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE),2) as SCORE
FROM REST_INFO INFO INNER JOIN REST_REVIEW REVIEW 
ON INFO.REST_ID = REVIEW.REST_ID 
WHERE ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
HAVING SCORE
ORDER BY SCORE DESC , FAVORITES DESC